window.SCAN_DATA = {
  projects: [
    {
      ProjectName: "GCI 2026 - IDS_Review",
      ProjectCode: "GCI-2026",
      ProjectStatus: "Completed",
      TestingProgress: "100%",
      TestCompleted: "Yes",
      StartDate: "2026-07-27",
      EndDate: "2026-08-01",
      TestDurationDays: 5,
      TotalFindings: 5,
      OpenFindings: 4,
      ClosedFindings: 1,
      RetestFindings: 0,
      Critical: 2,
      CriticalOpen: 2,
      High: 1,
      HighOpen: 1,
      Medium: 1,
      MediumOpen: 1,
      Low: 1,
      LowOpen: 0,
      Info: 0,
      InfoOpen: 0,
      TotalAssets: 3
    },
    {
      ProjectName: "NET 2026 - Network_Perimeter",
      ProjectCode: "NET-2026",
      ProjectStatus: "Completed",
      TestingProgress: "100%",
      TestCompleted: "Yes",
      StartDate: "2026-07-14",
      EndDate: "2026-07-25",
      TestDurationDays: 11,
      TotalFindings: 7,
      OpenFindings: 6,
      ClosedFindings: 1,
      RetestFindings: 0,
      Critical: 2,
      CriticalOpen: 2,
      High: 1,
      HighOpen: 1,
      Medium: 2,
      MediumOpen: 1,
      Low: 1,
      LowOpen: 1,
      Info: 1,
      InfoOpen: 1,
      TotalAssets: 5
    },
    {
      ProjectName: "PAY 2026 - Payment_Systems",
      ProjectCode: "PAY-2026",
      ProjectStatus: "Completed",
      TestingProgress: "100%",
      TestCompleted: "Yes",
      StartDate: "2026-06-16",
      EndDate: "2026-06-27",
      TestDurationDays: 11,
      TotalFindings: 8,
      OpenFindings: 6,
      ClosedFindings: 2,
      RetestFindings: 0,
      Critical: 2,
      CriticalOpen: 2,
      High: 2,
      HighOpen: 1,
      Medium: 2,
      MediumOpen: 2,
      Low: 1,
      LowOpen: 0,
      Info: 1,
      InfoOpen: 1,
      TotalAssets: 7
    },
    {
      ProjectName: "APP 2026 - ExtApp_Review",
      ProjectCode: "APP-2026",
      ProjectStatus: "Completed",
      TestingProgress: "100%",
      TestCompleted: "Yes",
      StartDate: "2026-07-07",
      EndDate: "2026-07-18",
      TestDurationDays: 11,
      TotalFindings: 7,
      OpenFindings: 6,
      ClosedFindings: 1,
      RetestFindings: 0,
      Critical: 1,
      CriticalOpen: 1,
      High: 2,
      HighOpen: 2,
      Medium: 2,
      MediumOpen: 1,
      Low: 1,
      LowOpen: 1,
      Info: 1,
      InfoOpen: 1,
      TotalAssets: 4
    }
  ],

  findings: [
    {
      ProjectName: "GCI 2026 - IDS_Review",
      ProjectCode: "GCI-2026",
      ProjectStartDate: "2026-07-27",
      ProjectEndDate: "2026-08-01",
      FindingName: "Hardcoded Credentials in Mobile Application",
      Description: "Credentials were found embedded within the mobile application package.",
      Severity: "Critical",
      SeveritySort: 1,
      Status: "Open",
      SLADueDate: "2026-08-20",
      SLAStatus: "Past Due",
      SLAStatusSort: 3,
      DaysToTarget: 0,
      DaysOverdue: 7,
      SLADays: "2026-08-20T10:00:00.000Z",
      FindingID: "GCI-FINDING-001",
      AlternateID: "GCI-2026-1",
      CVSSv3: 9.8,
      ReadyForRetest: "No",
      Created: "2026-08-05",
      StatusUpdated: "2026-08-05",
      AffectedAssetCount: 3
    },
    {
      ProjectName: "NET 2026 - Network_Perimeter",
      ProjectCode: "NET-2026",
      ProjectStartDate: "2026-07-14",
      ProjectEndDate: "2026-07-25",
      FindingName: "Unencrypted Data Transmission over HTTP",
      Description: "Sensitive traffic was transmitted through an unencrypted HTTP connection.",
      Severity: "Critical",
      SeveritySort: 1,
      Status: "Open",
      SLADueDate: "2026-08-14",
      SLAStatus: "Past Due",
      SLAStatusSort: 3,
      DaysToTarget: 0,
      DaysOverdue: 13,
      SLADays: "2026-08-14T09:00:00.000Z",
      FindingID: "NET-FINDING-001",
      AlternateID: "NET-2026-1",
      CVSSv3: 9.4,
      ReadyForRetest: "No",
      Created: "2026-07-26",
      StatusUpdated: "2026-07-26",
      AffectedAssetCount: 4
    },
    {
      ProjectName: "PAY 2026 - Payment_Systems",
      ProjectCode: "PAY-2026",
      ProjectStartDate: "2026-06-16",
      ProjectEndDate: "2026-06-27",
      FindingName: "Payment Data Stored in Application Logs",
      Description: "Sensitive payment information was visible within application log files.",
      Severity: "High",
      SeveritySort: 2,
      Status: "Open",
      SLADueDate: "2026-09-01",
      SLAStatus: "Within SLA",
      SLAStatusSort: 1,
      DaysToTarget: 5,
      DaysOverdue: 0,
      SLADays: "2026-09-01T08:00:00.000Z",
      FindingID: "PAY-FINDING-001",
      AlternateID: "PAY-2026-1",
      CVSSv3: 8.1,
      ReadyForRetest: "No",
      Created: "2026-06-28",
      StatusUpdated: "2026-06-28",
      AffectedAssetCount: 5
    },
    {
      ProjectName: "APP 2026 - ExtApp_Review",
      ProjectCode: "APP-2026",
      ProjectStartDate: "2026-07-07",
      ProjectEndDate: "2026-07-18",
      FindingName: "Blind SQL Injection in User Search",
      Description: "The user-search parameter did not properly validate database input.",
      Severity: "Critical",
      SeveritySort: 1,
      Status: "Open",
      SLADueDate: "2026-08-30",
      SLAStatus: "Due Soon",
      SLAStatusSort: 2,
      DaysToTarget: 3,
      DaysOverdue: 0,
      SLADays: "2026-08-30T07:00:00.000Z",
      FindingID: "APP-FINDING-001",
      AlternateID: "APP-2026-1",
      CVSSv3: 9.8,
      ReadyForRetest: "No",
      Created: "2026-07-19",
      StatusUpdated: "2026-07-19",
      AffectedAssetCount: 2
    }
  ],

  appOwners: [
    {
      AppID: "APP-001",
      AppName: "Customer Web Portal",
      Team: "Web Engineering",
      TechLead: "Jordan Lee",
      Owner: {
        Name: "Alex Morgan",
        Email: "alex.morgan@example.com",
        Title: "Application Owner"
      }
    },
    {
      AppID: "APP-002",
      AppName: "Mobile Application",
      Team: "Mobile Engineering",
      TechLead: "Taylor Smith",
      Owner: {
        Name: "Casey Johnson",
        Email: "casey.johnson@example.com",
        Title: "Product Owner"
      }
    },
    {
      AppID: "APP-004",
      AppName: "Network Operations Platform",
      Team: "Network Security",
      TechLead: "Morgan Davis",
      Owner: {
        Name: "Riley Brown",
        Email: "riley.brown@example.com",
        Title: "System Owner"
      }
    },
    {
      AppID: "APP-005",
      AppName: "Payment Processing Platform",
      Team: "Payment Systems",
      TechLead: "Cameron Wilson",
      Owner: {
        Name: "Jamie Taylor",
        Email: "jamie.taylor@example.com",
        Title: "Application Owner"
      }
    }
  ]
};
